server:
  port: ${PORT:8083}
spring:
  application:
    name: api-catalog
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

info:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/